# Generated by Django 4.1.4 on 2022-12-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_dt",
                    models.DateTimeField(auto_now=True, verbose_name="Час створення"),
                ),
                (
                    "product_username",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Username"
                    ),
                ),
                (
                    "product_name",
                    models.CharField(max_length=100, verbose_name="Ім'я продавця"),
                ),
                (
                    "product_lastname",
                    models.CharField(max_length=100, verbose_name="Фамілія продавця"),
                ),
                (
                    "product_phone",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Номер телефону"
                    ),
                ),
                ("product_email", models.CharField(max_length=254, unique=True)),
                ("product_productname", models.CharField(max_length=100)),
                ("product_description", models.CharField(max_length=500)),
                ("product_media", models.FileField(upload_to="uploads/")),
            ],
            options={"verbose_name": "Товар", "verbose_name_plural": "Товари",},
        ),
    ]
