# Generated by Django 4.1.4 on 2023-01-01 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_email",
            field=models.CharField(max_length=254),
        ),
    ]
