# Generated by Django 4.1.4 on 2023-01-01 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_product_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_phone",
            field=models.CharField(max_length=20, verbose_name="Номер телефону"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_username",
            field=models.CharField(max_length=100, verbose_name="Username"),
        ),
    ]
