# Generated by Django 4.1.4 on 2023-01-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_alter_product_product_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_description",
            field=models.CharField(max_length=500, verbose_name="Опис товару"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_email",
            field=models.CharField(
                max_length=254, verbose_name="Електронна пошта продавця"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_lastname",
            field=models.CharField(max_length=100, verbose_name="Прізвище продавця"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_media",
            field=models.ImageField(
                upload_to="images/", verbose_name="Фотографії товару"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_productname",
            field=models.CharField(max_length=100, verbose_name="Назва товару"),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_username",
            field=models.CharField(max_length=100, verbose_name="Ім'я користувача"),
        ),
    ]
